// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/lakhansamani/forks/training/InvoiceApp/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/lakhansamani/forks/training/InvoiceApp/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('InvoiceApp', appParameters);
});
require('/Users/lakhansamani/forks/training/InvoiceApp/index.android.js');